export const ALL_PROPERTIES = [
  {
      id: 0,
      rent: false,
      img: "../img/house5.jpg",
      address: "123 Palm Canyon Dr",
      description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",        price: "$2000/month",
      lat: 33.827680,
      lng: -116.529450,
      beds: 3,
      baths: 2,
      photos: ["../img/interiors/livingroom5.jpg","../img/interiors/kitchen5.jpg","../img/interiors/bedroom9.jpg","../img/interiors/bedroom10.jpg"]
  },
  {
      id: 1,
      rent: false,
      img: "../img/house6.jpg",
      address: "789 Indian Canyon Dr",
      description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
      price: "$1500/month",
      lat: 33.827680,
      lng: -116.529450,
      beds: 3,
      baths: 2,
      photos: ["../img/interiors/livingroom6.jpg","../img/interiors/kitchen6.jpg","../img/interiors/bedroom11.jpg","../img/interiors/bedroom12.jpg"]
  },
  {
      id: 2,
      rent: false,
      img: "../img/house7.jpg",
      address: "644 Gene Autry Trail",
      description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
      price: "$3000/month",
      lat: 33.827680,
      lng: -116.529450,
      beds: 3,
      baths: 2,
      photos: ["../img/interiors/livingroom7.jpg","../img/interiors/kitchen7.jpg","../img/interiors/bedroom13.jpg","../img/interiors/bedroom14.jpg"]
  },
  {
      id: 3,
      rent: false,
      img: "../img/house8.jpg" ,
      address: "332 Sunrise Rd",
      description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
      price: "2500/month",
      lat: 33.827680,
      lng: -116.529450,
      beds: 3,
      baths: 2,
      photos: ["../img/interiors/livingroom8.jpg","../img/interiors/kitchen8.jpg","../img/interiors/bedroom15.jpg","../img/interiors/bedroom16.jpg"]
  },
  {
    id: 4,
    rent: true,
    img: "../img/house1.jpg",
    address: "354 Terra Vita",
    description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
    price: "$650,000",
    lat: 33.827680,
    lng: -116.529450,
    beds: 3,
    baths: 2,
    photos: ["../img/interiors/livingroom1.jpg","../img/interiors/kitchen1.jpg","../img/interiors/bedroom1.jpg","../img/interiors/bedroom2.jpg"]
},
{
    id: 5,
    rent: true,
    img: "../img/house2.jpg",
    address: "789 Indian Canyon Dr",
    description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
    price: "$750,000",
    lat: 33.827680,
    lng: -116.529450,
    beds: 3,
    baths: 2,
    photos: ["../img/interiors/livingroom2.jpg","../img/interiors/kitchen2.jpg","../img/interiors/bedroom3.jpg","../img/interiors/bedroom4.jpg"]
},
{
    id: 6,
    rent: true,
    img: "../img/house3.jpg",
    address: "644 Gene Autry Trail",
    description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",        
    price: "$850,000",
    lat: 33.827680,
    lng: -116.529450,
    beds: 3,
    baths: 2,
    photos: ["../img/interiors/livingroom3.jpg","../img/interiors/kitchen3.jpg","../img/interiors/bedroom5.jpg","../img/interiors/bedroom6.jpg"]
},
{
    id: 7,
    rent: true,
    img: "../img/house4.jpg" ,
    address: "332 Sunrise Rd",
    description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex sit amet metus interdum bibendum non non sem. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ultricies elit, non euismod odio. Pellentesque a accumsan elit. Morbi nec justo venenatis, lacinia leo vulputate, malesuada turpis. Sed iaculis imperdiet porttitor. Fusce sollicitudin, massa eu commodo vehicula, sem erat pulvinar dolor, sit amet tincidunt dolor ipsum eu turpis. Suspendisse quis ligula tincidunt, efficitur felis et, pellentesque risus. Cras auctor nunc non diam condimentum, vitae fermentum odio ullamcorper. Donec vestibulum ligula sit amet luctus sagittis. Integer consequat lacus ac augue gravida, a convallis massa molestie. Nulla tristique quis eros in vestibulum. Ut volutpat lectus libero, et accumsan nulla mattis ut. Nulla pharetra dictum elit, a convallis nunc condimentum in.",
    price: "$950,000",
    lat: 33.827680,
    lng: -116.529450,
    beds: 3,
    baths: 2,
    photos: ["../img/interiors/livingroom4.jpg","../img/interiors/kitchen4.jpg","../img/interiors/bedroom7.jpg","../img/interiors/bedroom8.jpg"]
}


]